### PR TITLE
Conda build recipe

### PR DESCRIPTION
**Pull request by cgr71ii**
Necessary files in order to build a conda package.

A conda package has been already released: https://anaconda.org/bitextor/fastspell.

### CODE REVIEW

**Comment by ZJaume** [comment]
Trying the conda package installed with `conda install -c conda-forge -c bitextor fastspell`

Fails when invoking the command

```python
Traceback (most recent call last):
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fastspell/fastspell.py", line 12, in <module>
    from . import FastSpell
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fastspell/FastSpell.py", line 3, in <module>
    import fasttext
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fasttext/__init__.py", line 12, in <module>
    from .FastText import train_supervised
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fasttext/FastText.py", line 12, in <module>
    import fasttext_pybind as fasttext
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fasttext_pybind.cpython-310-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/bin/fastspell", line 5, in <module>
    import fastspell.fastspell as fastspell
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fastspell/__init__.py", line 5, in <module>
    from . import fastspell
  File "/home/jzaragoza/miniconda3/envs/bicleaner-conda/lib/python3.10/site-packages/fastspell/fastspell.py", line 14, in <module>
    import FastSpell
ModuleNotFoundError: No module named 'FastSpell'
```

**Comment by cgr71ii** [comment]
I have tried the same installation in a clean environment and I don't get the error. How did you create the conda environment? I ran:

```bash
conda create -n fastspell -y
conda activate fastspell
conda install -c conda-forge -c bitextor fastspell
```

`which fastspell`: /home/cgarcia/miniconda3/envs/fastspell/bin/fastspell

When I run `fastspell`:

```
usage: fastspell [-h] [--aggr] [--cons] [-q] [--debug] [--logfile LOGFILE] [-v] lang [input] [output]
fastspell: error: the following arguments are required: lang
```

Fastspell python example:

```python
# Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0] on linux
# Type "help", "copyright", "credits" or "license" for more information.
>>> from fastspell import FastSpell
>>> fsobj = FastSpell.FastSpell("en", mode="cons")
WARNING:root:Downloading FastText model...
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
>>> fsobj.getlang("Hello, world")
'en'
>>> fsobj.getlang("Hola, mundo")
'es'
```

`conda config --show channels`:
```
channels:
  - conda-forge
  - defaults
```

`pip list`:
```
Package    Version
---------- ---------
click      8.0.4
fastspell  0.1.5
fasttext   0.9.2
hunspell   0.5.5
joblib     1.1.0
numpy      1.22.3
pip        22.0.4
pybind11   2.9.1
PyYAML     6.0
regex      2022.3.15
sacremoses 0.0.49
setuptools 61.2.0
six        1.16.0
tqdm       4.63.1
urllib3    1.26.9
wheel      0.37.1
```

`conda list`:
```
# packages in environment at /home/cgarcia/miniconda3/envs/fastspell:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aoo-mozilla-en-dict-au    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-ca    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-gb    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-us    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-za    2020.06.01                    1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
click                     8.0.4                    pypi_0    pypi
fastspell                 0.1.5                    pypi_0    pypi
fasttext                  0.9.2                    pypi_0    pypi
gettext                   0.19.8.1          h73d1719_1008    conda-forge
hunspell                  0.5.5                    pypi_0    pypi
hunspell-en               2020.06.01                    1    conda-forge
joblib                    1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
numpy                     1.22.3                   pypi_0    pypi
openssl                   3.0.2                h166bdaf_1    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pybind11                  2.9.1                    pypi_0    pypi
python                    3.10.4          h2660328_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2022.3.15                pypi_0    pypi
sacremoses                0.0.49                   pypi_0    pypi
setuptools                61.2.0          py310hff52083_1    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.37.1               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.63.1                   pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

`python -c "import fastspell; print(fastspell.__file__)"`: /home/cgarcia/miniconda3/envs/fastspell/lib/python3.10/site-packages/fastspell/__init__.py

**Comment by cgr71ii** [comment]
The problem seems to be related to your GLIBC version, what leads to the last exception. I've been looking for a bit of information about this problem, and it seems that the problem is not related to the package itself, but to your GLIBC problem. This means, if I'm not wrong, that the problem might/should be solved on your side, what means to update your system, what it should be easier and cause less problems that update GLIBC (https://stackoverflow.com/questions/11107263/how-compatible-are-different-versions-of-glibc is an example where they discuss this same topic for a conda package).

This package which I uploaded to Anaconda repo were built on a Ubuntu 20.04.3 system, GLIBC 2.31 ("Ubuntu GLIBC 2.31-0ubuntu9.7" specifically according to `ldd --version ldd`).

According to https://stackoverflow.com/questions/11107263/how-compatible-are-different-versions-of-glibc, this package should work with systems which have GLIBC>=2.31 (likely, not for sure).

Another solution might be to upload multiple packages with different GLIBC versions in order to be able to select the higher version possible, or just upload a package with a low GLIBC version, what I think it should not be an option since older GLIBC versions might contain bugs/optimization issues. This is the taken decision by many packages, but not for GLIBC, but for python version or other dependencies (e.g. [pytorch 1.11.0 -> python 3.8 cuda 11.5 cudnn 8.3.2](https://anaconda.org/pytorch/pytorch/1.11.0/download/linux-64/pytorch-1.11.0-py3.8_cuda11.5_cudnn8.3.2_0.tar.bz2) and [pytorch 1.11.0 -> python 3.9 cuda 11.1 cudnn 8.0.5](https://anaconda.org/pytorch/pytorch/1.11.0/download/linux-64/pytorch-1.11.0-py3.9_cuda11.1_cudnn8.0.5_0.tar.bz2)). I guess that the option of upload multiple packages for different version and/or dependencies is not a bad decision, but I guess that in the case of GLIBC this is not done that often.

If I'm wrong at any point, I'd like to know and try to solve it.

BTW: I have tried the package on multiple devices and it worked on all them, but it is the expected since all of them were Ubuntu 20.04

**Review by ZJaume — APPROVED** [review]
Building from source works at the machine that was giving problems. So, I think it can be merged.

**Comment by mbanon** [comment]
Merged! Thank you, guys!

**Pull request merged**
